spring:
  application:
    name: DemoLibrary
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1434;encrypt=true;trustServerCertificate=true;databaseName=DemoLibrary
    username: demoLibraryUser
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          audiences:
            - https://DemoLibraryAuthApi
          issuer-uri: https://dev-ijzwld8inlw3zyy2.eu.auth0.com/

auth0:
  domain: dev-ijzwld8inlw3zyy2.eu.auth0.com
  token-url: https://dev-ijzwld8inlw3zyy2.eu.auth0.com/oauth/token
  client-id: j4hbaZVAfJKKEWPkqCM76NNNLBhHDB1W
  client-secret: FeP0dZkq_gkQXS8HkLhh0VxyR1fFSG4MkAZyeTqgr5UaWRhnXmiHY68W2Gy1mphw
  audience: https://DemoLibraryAuthApi