# Configurazione H2

spring.jackson.encoding=UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.force=true

version.lastApiVersion=1.0

frontend.domain=https://demoLibraryDomain:3000

spring.profiles.active=debug,dev,staging

security.require-ssl=true
