spring.application.name=DemoLibrary
# Configurazione H2
spring.datasource.url=jdbc:h2:mem:demoLibraryDb;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.platform=h2

# Mostra la console di H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurazione JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.encoding=UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.force=true

version.lastApiVersion=1.0


spring.security.oauth2.resourceserver.jwt.audiences: https://DemoLibraryAuthApi
spring.security.oauth2.resourceserver.jwt.issuer-uri:https://dev-ijzwld8inlw3zyy2.eu.auth0.com/

auth0.token-url= https://dev-ijzwld8inlw3zyy2.eu.auth0.com/oauth/token
auth0.client-id = j4hbaZVAfJKKEWPkqCM76NNNLBhHDB1W
auth0.client-secret = FeP0dZkq_gkQXS8HkLhh0VxyR1fFSG4MkAZyeTqgr5UaWRhnXmiHY68W2Gy1mphw
auth0.audience= https://DemoLibraryAuthApi