# Configurazione H2

spring.jackson.encoding=UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.force=true


frontend.domain=https://demoLibraryDomain:3000
version.lastApiVersion=1.0

security.require-ssl=true
server.ssl.certificate-private-key=classpath:./ssl/cert.key
server.ssl.certificate=classpath:./ssl/cert.crt

spring.data.redis.host: 192.168.2.105
spring.data.redis.password: default
spring.data.redis.port: 6379
spring.data.redis.database= 0
spring.data.redis.time-to-live=60000