spring:
  application:
    name: DemoLibrary
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: update
    show-sql: true

auth0:
  domain: ${AUTH0_DOMAIN}
  token-url: ${AUTH0_TOKEN_URL}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}