spring.application.name=DemoLibrary
# Configurazione H2
spring.datasource.url=jdbc:h2:mem:demoLibraryDb;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.platform=h2

spring.jackson.encoding=UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.force=true

version.lastApiVersion=1.0
