spring:
  application:
    name: DemoLibrary

  security:
    oauth2:
      resource-server:
        jwt:
          audiences:
            - https://DemoLibraryAuthApi
          issuer-uri: https://dev-ijzwld8inlw3zyy2.eu.auth0.com/
