# Configurazione H2

spring.jackson.encoding=UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.force=true


frontend.domain=https://demoLibraryDomain:3000
version.lastApiVersion=1.0

security.require-ssl=true
server.ssl.certificate-private-key=classpath:./ssl/cert.key
server.ssl.certificate=classpath:./ssl/cert.crt
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath*:graphql/**/
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.max-age=1800s