spring.application.name=DemoLibrary
# Configurazione H2
spring.datasource.url=jdbc:h2:mem:demoLibraryDb;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.platform=h2

# Mostra la console di H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurazione JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.encoding=UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.force=true

version.lastApiVersion=1.0

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://my-auth-server.com